### ISSUE TITLE
why do you use RabbitMQ

### ISSUE THREAD

**Issue by MaryLilian** [EliasSantiago/app-bank-transactions#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose RabbitMQ in your project instead of others like ZeroMQ or Kafka, are there any special features but others dont have it. Can you share me  it. I am wondering when I should choose RabbitMQ instead of others like ZeroMQ or Kafka

**Comment by EliasSantiago** [comment]
Hello. I chose RabbitMQ because I'm studying a bit about messaging system. Soon I will study Kafka and also Amazon SQS.
